version: "2.1"
services:
  live-streaming-origin:
    image: docker.io/unifiedstreaming/live-streaming-origin:stable
    ports:
      - 80:80
    environment:
      - LOG_LEVEL=debug
      - USP_LICENSE_KEY=$USP_LICENSE_KEY
      - PUB_POINT_NAME=channel1
      - PUB_POINT_OPTS=--archiving=1 --archive_length=3600 --archive_segment_length=600 --dvr_window_length=1800 --restart_on_encoder_reconnect --hls.minimum_fragment_length=48/25 --hls.client_manifest_version=4 --hls.no_audio_only --mpd.minimum_fragment_length=48/25 --mpd.segment_template=time
    healthcheck:
      test: kill -0 1
      interval: 2s
      timeout: 5s
      retries: 30
  live-streaming-ffmpeg:
    image: docker.io/unifiedstreaming/live-streaming-ffmpeg:stable
    environment:
      - PUB_POINT_URI=http://live-streaming-origin/channel1/channel1.isml
      - 'TRACKS={ "video": [ { "width": 1280, "height": 720, "bitrate": "300k", "codec": "libx264", "framerate": 25, "gop": 48, "timescale": 25 },{ "width": 480, "height": 360, "bitrate": "100k", "codec": "libx264", "framerate": 25, "gop": 48, "timescale": 25 } ], "audio": [ { "samplerate": 48000, "bitrate": "64k", "codec": "aac", "language": "eng", "timescale": 48000, "frag_duration_micros": 1920000 },{ "samplerate": 48000, "bitrate": "64k", "codec": "aac", "language": "dut", "timescale": 48000, "frag_duration_micros": 1920000 } ] }'
    depends_on:
      live-streaming-origin:
        condition: service_healthy
